from os.path import realpath
from os.path import split as pathsplit
from os.path import basename
import subprocess
from snakemake.remote.FTP import RemoteProvider as FTPRemoteProvider
from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider
import sys

# Block annoying warnings
if not sys.warnoptions:
    import warnings
    warnings.simplefilter("ignore")

# Meta
__author__ = "Matt Lawlor"

# Setup
shell.executable("/bin/bash")


# Remotes
HTTP = HTTPRemoteProvider()
FTP = FTPRemoteProvider()

# DETERMINE REMOTE OR LOCAL RESOURCE
def determine_resource(path):
    if "ftp://" in path:
         return FTP.remote(path, immediate_close = True)
    elif "http://" in path:
         return HTTP.remote(path)
    elif "https://" in path:
         return HTTP.remote(path)
    else:
        return path

singularity: "docker://continuumio/miniconda3"
configfile: "config/config.yaml"
pepfile: "config/pep.yaml"

rule all:
    input:
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.


rule all_custom_genome:
    input:
        "results/custom-genome/combined.fixed.gtf",
        "results/custom-genome/combined.fasta"

rule all_cellranger:
    input:
        expand("results/cellranger/{s}.done", s=[x.sample_name for x in pep.samples if x.assay == "10X"]),
        #expand("results/fastq-dump-10x/{s}/", s=[x.sample_name for x in pep.samples if x.assay == "10X"])

include: "rules/custom-genome.smk"
include: "rules/cellranger.smk"
