


# Section 4


```{r f4a, fig.cap='Figure 4A: Expression of genes associated with primary spermatocyte expression program and Y activation.',  out.height='6in', out.width='7in',  dev.args = list(ragg_png= list(scaling=1)) }
ylinked <- unique(gtf %>% filter(seqnames == 'Y' & type == 'mRNA') %>% pull(gene_symbol)) %>%
  tibble(gene_symbol = ., group='y-linked')
tmac <- c('aly','wuc','tomb') %>% tibble(gene_symbol = ., group='tMAC')
ttaf <- c('sa') %>% tibble(gene_symbol = ., group='tTAF')
tbrd <- c('tbrd-1','tbrd2') %>% tibble(gene_symbol = ., group='tBRD')
tplus <- c('tplus3a','tplus3b') %>% tibble(gene_symbol = ., group='tPAF')

male.meiosis1.associated <- bind_rows(ylinked, tmac, ttaf, tbrd, tplus)

male.meiosis1.associated_df <- map_df(w1118.obs %>% 
                                        collect() %>% 
                                        pull(clusters) %>%
                                        unique() %>% 
                                        as.list %>% 
                                        set_names(.,.),
                                      ~{filter(w1118.expr, clusters == . & gene_symbol %in% male.meiosis1.associated$gene_symbol) %>% collect()}) %>%
  left_join(collect(w1118.obs), by=c(index='X1','cell_type'='cell_type')) %>%
  ungroup() %>%
  left_join(male.meiosis1.associated)


male.meiosis1.associated_df %>%
  dplyr::select(index, gene_symbol, expression, clusters2, group) %>%
  group_by(gene_symbol, clusters2, group) %>%
  mutate(pct.expressing = sum(expression > 0)/n(), mean.expression=mean(expression)) %>%
  summarize(pct.expressing = unique(pct.expressing), mean.expression = unique(mean.expression)) %>%
  ungroup() %>%
  ggplot(aes(gene_symbol, clusters2)) +
    geom_point(aes(size=pct.expressing, fill=mean.expression), shape=21) +
  scale_fill_fermenter(palette = 8, direction = 1, name='Log1p normalized UMIs', guide=guide_legend(label.position = 'bottom', title.position = 'top')) +
  scale_size(range=c(0, rel(5)), name='Proportion expressing', guide=guide_legend(label.position = 'bottom', title.position = 'top')) +
  theme_minimal()  +
  theme(legend.position = 'bottom') +
  theme(axis.text.x = element_text(angle=45, hjust=1)) +
  theme(axis.text.y = element_text(size=rel(1.2),)) +
  theme(aspect.ratio = 1.7, legend.text = element_text(size=rel(0.5)), legend.title = element_text(size=rel(0.5))) +
  coord_flip() +
  xlab('') + ylab('')
```


\newpage

```{r}
library(textrank)
library(udpipe)

tagger <- udpipe_download_model("english")
tagger <- udpipe_load_model(tagger$file_model)

mod.kw <- w1118.gep_enr %>%
  filter(weight01 < 0.05) %>%
  collect() %>%
  group_by(cluster, ont) %>%
  do(as.data.frame(udpipe_annotate(tagger, pull(.,Term)))) %>%
  group_by(cluster, ont) %>%
  do(as.data.frame(textrank_keywords(.$lemma, relevant = .$upos %in% c('NOUN','ADJ'),ngram_max = 3)$keywords)) %>%
  filter(ngram > 1 & freq >1) %>%
  ungroup()

mod.kw <- mod.kw %>% 
  arrange(cluster, desc(ont), desc(ngram), freq) %>% 
  group_by(cluster, ont) %>% slice_head(n=1) %>% 
  group_by(cluster) %>% 
  summarize(descriptor=paste(rev(keyword), collapse = '-')) %>%
  complete(cluster=full_seq(cluster,1), fill = list(descriptor='unknown')) %>%
  mutate(title=paste(cluster,descriptor,sep = '/'))

ave.usage.df <- w1118.gep_usage %>% 
  collect() %>%
  left_join(dplyr::select(collect(w1118.obs),X1, clusters2)) %>%
  left_join(mod.kw, ., by=c(cluster='cons')) %>%
  group_by(cluster,title, clusters2) %>%
  summarize(med.usage = median(usage), mean.usage=mean(usage))
```


```{r s4a, results='asis'}
most.used.modules <- ave.usage.df %>%
  group_by(clusters2) %>%
  top_n(3, med.usage) %>%
  mutate(rank = dense_rank(-med.usage)) %>%
  arrange(clusters2, rank) %>%
  ungroup()

(most.used.modules %>%
  dplyr::select(title, clusters2, rank) %>%
  group_by(clusters2) %>%
  gt() %>%
  tab_options(row_group.background.color =  'lightgray', column_labels.hidden = T) %>%
  tab_header(title = 'Supp. Fig. 4A: Most utilized GEPs', subtitle = "Table shows GEPs most expressed by each cell cluster. Because many discovered GEPs are enriched for multiple GO terms, names for each GEP are generated from  keywords frequently found in the descriptions for all enriched terms.") %>%
  tab_style(cell_text(indent = px(50)),locations = cells_body(columns = 'title'))
  )%>%
  as_latex() %>%
  as.character() %>%
  cat()
  
```

\newpage


```{r f4b, fig.cap='Figure 4B: GEP associated with chromatin modification expressed in late spermatogonia.'}
chrom_mod_clust <- w1118.gep_enr %>%
  filter(weight01 < 0.05) %>%
  collect() %>%
  arrange(-score) %>%
  filter(str_detect(Term,regex('methyl',ignore_case = T)) | str_detect(Term,regex('histo',ignore_case = T))) %>%
  dplyr::select(cluster, Term) %>% distinct() %>%
  #filter(cluster %in% c(7,26,38)) %>%
  pull(cluster) %>% unique() %>% head(1)


w1118.gep_usage %>%
  filter(cons %in% chrom_mod_clust) %>%
  collect() %>%
  left_join(mod.kw, by=c(cons='cluster')) %>%
  left_join(collect(w1118.obs)) %>%
  arrange(cons, usage) %>%
  group_split(cons) %>%
  map(.f = function(x) {
    midpoint <- median(x$usage)
    title <- unique(x$title)
    ggplot(x, aes(X_umap1,X_umap2, color=usage)) +
      geom_point(size=0.75) +
      scale_color_gradient2(low='blue', mid='lightgray',high='red', midpoint = midpoint) +
      theme_classic() +
      coord_fixed() +
      ggtitle(title) +
      theme(title = element_text(size=rel(0.8)))
  }) %>%
  walk(print)
```


```{r s4b, fig.cap = 'Supp. Fig. 4B: GO Term enrichment of late spermatogonia GEP.', out.height='3in', out.width='3in', fig.dim=c(3,3)}
w1118.gep_enr %>%
  filter(weight01 < 0.05 & cluster %in% chrom_mod_clust) %>%
  collect() %>%
  arrange(-score) %>%
  group_by(ont) %>%
  top_n(10, score) %>%
  ggplot(aes(score, reorder(Term, score))) +
  geom_col(aes(fill = score), color='black') +
  facet_wrap(~ont, scales='free', ncol=1) +
  theme_classic() +
  theme(aspect.ratio = 2.5, legend.position = 'above') +
  xlab('log10(pval)') +
  scale_fill_fermenter(direction = 1, palette = 3, name='log10(pval)') +
  scale_x_continuous(expand=c(0,0)) +
  theme(axis.text=element_text(size=rel(1.25)), axis.text.y=element_text(size=rel(1))) +
  ylab("")
```


```{r s4c, fig.cap = "Supp. Fig. 4C: TE candidates for RNA-FISH experiment chosen from among top expressed TEs in the TEP-expressing cell cluster."}
tep.tes <- tep.members[!str_detect(tep.members,'FBgn')]

tep_te_expr_df <- map_df(as.list(unique(pull(collect(w1118.obs),'clusters'))) %>% set_names(.,.),
       ~{filter(w1118.expr, (clusters == .) & (gene_id %in% tep.tes)) %>% collect()}) %>%
  dplyr::select(index, gene_id, expression, clusters) %>%
  mutate(clusters = as.character(clusters)) %>%
  mutate(umis = exp(expression) - 1) %>%
  mutate(expression=log2(umis + 1))

top_tep_te_rnk_df <- tep_te_expr_df %>%
  left_join(collect(w1118.obs), by=c(index='X1',clusters='clusters')) %>%
  group_by(gene_id, clusters2, clusters) %>%
  summarize(mean_expr = mean(expression)) %>%
  ungroup() %>%
  group_by(clusters2) %>%
  mutate(rnk = dense_rank(-mean_expr)) %>%
  arrange(clusters2,rnk) %>%
  filter(rnk <= 20) %>%
    filter(clusters==8)

tep_te_expr_df %>%
    filter(clusters==8 & gene_id %in% pull(filter(top_tep_te_rnk_df, clusters==8), gene_id)) %>%
  left_join(collect(w1118.obs), by=c(index='X1',clusters='clusters')) %>%
ggplot(aes(reorder(gene_id,expression),expression, fill=clusters2)) +
  scale_fill_brewer(type = 'qual', palette = 3) +
  #stat_summary(geom='crossbar',fun.data = mean_se) +
  geom_boxplot() +
  theme_classic() +
    theme(aspect.ratio = 1, 
          axis.text.x=element_text(angle=0, hjust=0.5)) +
  facet_wrap(~clusters2,scales='free') +
  ylab('log2(normalized UMIs)') + xlab('') +
  guides(fill=F) +
  coord_flip()
```


```{r s4d, fig.cap="Supp. Fig. 4D: Two TEs were chosen from highly expressed candidates based on their selective expression in TEP-expressing cells."}
other_cluster_tep_te_rnk_df <- tep_te_expr_df %>%
  filter(gene_id %in% pull(filter(top_tep_te_rnk_df, clusters==8),gene_id)) %>%
  left_join(collect(w1118.obs), by=c(index='X1',clusters='clusters')) %>%
  filter(clusters !=8 ) %>%
    group_by(gene_id) %>%
  summarize(mean_expr = mean(expression)) %>%
  arrange(mean_expr)

tep_te_expr_df %>%
  filter(gene_id %in% pull(filter(top_tep_te_rnk_df, clusters==8),gene_id)) %>%
  left_join(collect(w1118.obs), by=c(index='X1',clusters='clusters')) %>%
  arrange(expression) %>%
  filter(gene_id %in% head(other_cluster_tep_te_rnk_df$gene_id,4)) %>%
  filter(gene_id %in% c('ACCORD2','QUASIMODO2')) %>%
  ggplot(aes(X_umap1, X_umap2, color=expression)) +
    geom_point(size=0.75) +
    facet_wrap(~gene_id) +
  scale_color_gradient2(low='steelblue', mid='lightgray',high='tomato', midpoint = 3) +
  theme_classic() +
  coord_fixed()
```

```{r s4e, out.height="11in", fig.dim=c(10,10), fig.cap='Supp. Fig. B'}
markers2display <- c('EAChm','aly','ACCORD2','QUASIMODO2')

map_df(w1118.obs %>% collect() %>% pull(clusters) %>% unique() %>% as.list %>% set_names(.,.),
       ~{filter(w1118.expr, clusters == . & gene_symbol %in% markers2display) %>% collect()}) %>%
left_join(collect(w1118.obs), by=c(index='X1','cell_type'='cell_type')) %>%
  ungroup() %>%
  #group_by(cell_type) %>%
  mutate(ord = dense_rank(cell_type)) %>%
  mutate(gene_symbol = fct_relevel(gene_symbol, markers2display)) %>%
  ggplot(aes(fct_reorder(clusters2, ord),expression)) +
  #geom_boxplot(aes(fill=clusters2)) +
  geom_violin(aes(fill=clusters2),draw_quantiles = c(0.5),scale = 'width') +
  facet_wrap(~gene_symbol, ncol = 1, scales = 'free_y') +
  scale_fill_brewer(type='qual',palette = 8, name="") +
  theme_classic() +
  theme(plot.caption= element_text(hjust=0.5, face='italic', size=rel(1.2)), axis.title = element_text(size = rel(1.2)), axis.text.y = element_text(size=rel(1.2)), axis.text.x=element_text(angle=90, hjust=1, vjust=0.5, size=rel(1.2)),aspect.ratio = 0.1) +
  xlab('') + guides(fill=F)
```

