
# Section 1

```{r f1a, fig.cap='Figure 1A'}
umap_labs <- w1118.obs %>%
  group_by(clusters2) %>%
  collect() %>%
  summarise(x = mean(X_umap1), y=mean(X_umap2)) %>%
  ungroup() 

collect(w1118.obs) %>%
  ggplot(aes(X_umap1, X_umap2)) +
  geom_point(aes(color=clusters2), size=rel(1)) +
  scale_color_brewer(type='qual',palette='Set3', name='') +
  theme_classic() +
  coord_fixed(xlim = c(-15, 8)) +
  theme(legend.position = 'right') +
  labs(color="") +
  geom_text(data=umap_labs, aes(x + sign(x) *1, y, label=clusters2), face='bold', size=rel(3)) +
  theme(plot.caption= element_text(hjust=0.5, face='italic')) +
  xlab("UMAP1") + ylab("UMAP2") +
    theme(plot.caption= element_text(hjust=0.5, face='italic', size=rel(1.2)), axis.title = element_text(size = rel(1.2)), axis.text = element_text(size=rel(1.5)))
```

```{r f1b, out.height="11in", fig.dim=c(10,10), fig.cap='Figure 1B'}
markers2display <- c('bam','vas', 'aly','sa', 'nord','Fas3','tj','Wnt4','rdo','Sox100B','ems')

map_df(w1118.obs %>% collect() %>% pull(clusters) %>% unique() %>% as.list %>% set_names(.,.),
       ~{filter(w1118.expr, clusters == . & gene_symbol %in% markers2display) %>% collect()}) %>%
left_join(collect(w1118.obs), by=c(index='X1','cell_type'='cell_type')) %>%
  ungroup() %>%
  #group_by(cell_type) %>%
  mutate(ord = dense_rank(cell_type)) %>%
  mutate(gene_symbol = fct_relevel(gene_symbol, markers2display)) %>%
  ggplot(aes(fct_reorder(clusters2, ord),expression)) +
  geom_violin(aes(fill=clusters2),draw_quantiles = c(0.5),scale = 'width') +
  facet_wrap(~gene_symbol, ncol = 1, scales = 'free_y') +
  scale_fill_brewer(type='qual',palette = 8, name="") +
  theme_classic() +
  theme(plot.caption= element_text(hjust=0.5, face='italic', size=rel(1.2)), axis.title = element_text(size = rel(1.2)), axis.text.y = element_text(size=rel(1.2)), axis.text.x=element_text(angle=90, hjust=1, vjust=0.5, size=rel(1.2)),aspect.ratio = 0.1) +
  xlab('') + guides(fill=F)
```
