pep_version: 2.0.0
sample_table: "sample_table.csv"
subsample_table:
  - "subsample_table_10X.csv"
  - "subsample_table_rnaseq.csv"
  - "subsample_table_isoseq.csv"
  - "subsample_table_chipseq.csv"
  - "subsample_table_srnaseq.csv"
